server:
  port: 8088  #端口
  context-path: /channel #项目访问路径

spring:
    datasource:
        name: test
        url: jdbc:mysql://rm-bp18ki525074c8ig6o.mysql.rds.aliyuncs.com:3306/dmflow?characterEncoding=utf8&useSSL=true # WARN SSL：在高版本需要指明是否进行SSL连接问题 useSSL=true
        username: dm_1qaz
        password: Dmflow_uat_wr
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20